Profile.destroy_all

Profile.create! [
	{
		first_name: "Aliko",
		middle_name: "",
		last_name: "Dangote",
		job: "CEO, Dangote Group",
		education: "Bachelor of Arts / Science, Al-Azhar University",
		age: 59,
		source1: "Cement",
		source2: "Sugar",
		source3: "Flour",
		net_worth: "3.4 Trillion",
		description: "Aliko Dangote, Africa's richest man, founded and chairs Dangote Cement, the continent's largest cement producer. In 2015 Dangote Cement launched new plants in Cameroon, Ethiopia, Zambia and Tanzania. The company produces more than 30 million metric tons annually, and plans to double capacity by 2018. Dangote owns about 90% of publicly-traded Dangote Cement through a holding company; this percentage exceeds the 80% ownership ceiling set by the Nigerian Stock Exchange.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/dangote.jpg")
	},
	{
		first_name: "Mike",
		middle_name: "",
		last_name: "Adenuga",
		job: "Chairman, Globacom",
		education: "Master of Business Administration, Pace University, New York",
		age: 63,
		source1: "Telecom",
		source2: "Oil",
		source3: "Self made",
		net_worth: "2 Trillion",
		description: "Nigeria's second richest man, built his fortune in telecom and oil production. His mobile phone network, Globacom, is the second largest operator in Nigeria with 32 million subscribers; it also has operations in Ghana and the Republic of Benin. A higher estimate of Globacom's revenues led Forbes to increase the value we assign to it. His exploration outfit, Conoil Producing, operates 6 oil blocks in the Niger Delta.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/mikeadenuga.jpg")
	},
	{
		first_name: "Folorunsho",
		middle_name: "",
		last_name: "Alakija",
		job: "Vice Chair, Famfa Oil",
		education: "",
		age: 65,
		source1: "Oil",
		source2: "Self made",
		source3: "",
		net_worth: "345 Billion",
		description: "Folorunsho Alakija is the vice chair of Famfa Oil, a Nigerian oil exploration company that has a 60% participating interest in block OML 127, part of the larger Agbami field, one of Nigeria's largest deepwater discoveries, about 70 miles offshore. Its partners include Chevron and Petrobras. Her first company was a fashion label that catered to Nigeria's elite women, including the wife of former military president, Ibrahim Babangida, who awarded Alakija's company an oil prospecting license.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/alakija.jpg")
	},
	{
		first_name: "Femi",
		middle_name: "",
		last_name: "Otedola",
		job: "Chairman, Forte Oil",
		education: "",
		age: 53,
		source1: "Gas stations",
		source2: "utilities",
		source3: "self made",
		net_worth: "229 Billion",
		description: "Femi Otedola of Nigeria is the controlling shareholder of publicly 
					 traded Forte Oil, an oil marketing and power generation company. 
					 Originally a Nigerian subsidiary of British Petroleum (BP), 
					 Forte Oil has more than 500 gas stations across the country. 
					 It owns oil storage depots and manufactures its own line of engine oils. 
					 In 2013, Otedola led the company to purchase a government-owned stake in a 
					 gas-fired power plant in Kogi state in central Nigeria.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/otedola.jpg")
	},
	{
		first_name: "Tony",
		middle_name: "",
		last_name: "Elumelu",
		job: "Investor",
		education: "",
		age: 53,
		source1: "Investments",
		source2: "Self made",
		source3: "",
		net_worth: "139 Billion",
		description: "Nigerian entrepreneur and investor Tony Elumelu owns a controlling interest in Transcorp, a publicly traded Nigerian conglomerate with interests in hospitality, agriculture, oil production and power generation. He came into the limelight in 1997 when he led a small group of investors to take over a small, floundering commercial bank in Lagos. He turned it profitable within a few years and in 2005 he merged it with the United Bank for Africa.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/elumelu.jpg")
	},
	{
		first_name: "Theophilus",
		middle_name: "",
		last_name: "Danjuma",
		job: "Founder, South Atlantic Petroleum",
		education: "Drop Out, Ahmadu Bello University",
		age: 77,
		source1: "Oil",
		source2: "Self made",
		source3: "",
		net_worth: "149 Billion",
		description: "Theophilus Danjuma is a former Nigerian defense minister and the founder of oil exploration company South Atlantic Petroleum, which owns upstream assets in Nigeria, Republic of Benin, the Central African Republic and Madagascar. He serves as the company's chairman; his wife, Daisy, is vice chairman. He also owns real estate plus a stake in Notore Chemical Industries, a manufacturer of urea fertilizer, as well as a stake in NALComet, one of Nigeria's largest shipping companies.",
		mycountry: "Nigeria",
		mystate: "Abuja",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/danjuma.jpg")
	},
	{
		first_name: "Abdulsamad",
		middle_name: "",
		last_name: "Rabiu",
		job: "Founder, BUA Group",
		education: "",
		age: 55,
		source1: "cement",
		source2: "sugar",
		source3: "self made",
		net_worth: "231 Billion",
		description: "Abdulsamad Rabiu is the founder of BUA Group, a Nigerian conglomerate active in sugar refining, cement production, real estate, logistics and port operations. Rabiu is expanding cement production. In September 2015, BUA signed a $600 million deal with Sinoma International Engineering, a Chinese cement equipment and engineering service provider, to construct a second production line at its flagship Obu cement plant, located in Edo State in the western part of Nigeria.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/rabiu.jpg")
	},
	{
		first_name: "Mohammed",
		middle_name: "",
		last_name: "Indimi",
		job: "Chairman, Oriental Energy Resources",
		education: "",
		age: 67,
		source1: "Oil",
		source2: "",
		source3: "self made",
		net_worth: "100 Billion",
		description: "Mohammed Indimi is the chairman and leading shareholder of Oriental Energy Resources, a privately held Nigerian oil exploration and production company he founded in 1990. Oriental currently has three projects offshore of Nigeria's Niger Delta region. Six of his children serve on the company's board. His net worth dropped from an estimated $670 million a year ago due to ongoing low oil prices.",
		mycountry: "Nigeria",
		mystate: "Maiduguri",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/indimi.jpg")
	},
	{
		first_name: "Jim",
		middle_name: "",
		last_name: "Ovia",
		job: "Founder, Zenith Bank",
		education: "",
		age: 65,
		source1: "Banking",
		source2: "",
		source3: "self made",
		net_worth: "110 Billion",
		description: "Jim Ovia is the founder of Zenith Bank, one of the largest commercial banks in Nigeria. He is the chairman and largest individual shareholder with a stake of slightly more than 9% stake. He also owns prime real estate across Nigeria, and mobile telecom operator Visafone, which has 3 million subscribers.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/ovia.jpg")
	},
	{
		first_name: "Orji",
		middle_name: "Uzor",
		last_name: "Kalu",
		job: "Founder, Slok Holding",
		education: "",
		age: 56,
		source1: "Diversified",
		source2: "",
		source3: "self made",
		net_worth: "66 Billion",
		description: "Orji Uzor Kalu is the founder of Slok Holding, a West African conglomerate with interests in shipping, banking, oil trading, manufacturing and the media. He got his start in business at age 19 after being expelled from a Nigerian university for spearheading a series of student riots. He borrowed $35 from his mother and started trading commodities like palm oil, rice and sugar. He diversified into furniture manufacturing and transportation and became a millionaire by the time he was 20. He hit the big time in the early 80s when the Nigerian military government awarded him lucrative contracts to import and supply arms and ammunition to Nigeria's military and defense forces.",
		mycountry: "Nigeria",
		mystate: "Abuja",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/uzorkalu.jpg")
	},
	{
		first_name: "Oba",
		middle_name: "",
		last_name: "Otudeko",
		job: "Founder, Honeywell Group",
		education: "Bachelor of Arts / Science, Leeds College of Commerce",
		age: 72,
		source1: "manufacturing",
		source2: "telecom",
		source3: "self made",
		net_worth: "110 Billion",
		description: "Oba Otudeko is the founder and chairman of Honeywell Group. The conglomerate's operations stretch across oil and gas, flour milling, real estate and marine transportation. Another piece of his fortune is in the oceanfront Radisson Blu in Lagos, Nigeria.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/otudeko.jpg")
	},
	{
		first_name: "Hakeem",
		middle_name: "Belo",
		last_name: "Osagie",
		job: "Chairman, Etisalat Nigeria",
		education: "Master of Business Administration, Harvard Business School",
		age: 61,
		source1: "telecom",
		source2: "",
		source3: "self made",
		net_worth: "119 Billion",
		description: "Hakeem Belo-Osagie is the chairman of Etisalat Nigeria, Nigeria's fourth largest mobile telecom network, with more than 18 million subscribers. His father was the gynecologist to the family of former Nigerian military president Ibrahim Babangida. Through that connection, he was able to secure a job as a Special Assistant to the Presidential Adviser on petroleum and energy and later as Special Assistant to the Minister of Petroleum and Energy, positions which he admits put him in a position to close on a few oil deals from where he made his first fortune.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/osagie.jpg")
	},
	{
		first_name: "Tunde",
		middle_name: "",
		last_name: "Folawiyo",
		job: "MD, Yinka Folawiyo group",
		education: "",
		age: 56,
		source1: "oil",
		source2: "telecom",
		source3: "",
		net_worth: "129 Billion",
		description: "Tunde Folawiyo is the managing director of the Yinka Folawiyo Group, conglomerate with interests in energy, agriculture, shipping, real estate and engineering. His father, Wahab Folawiyo, a well known Nigerian businessman and Islamic leader, started the group in 1957 as a commodities trading outfit and served as chairman until 2008 when he passed away. Folawiyo now calls the shots. The company's oil exploration firm, Yinka Folawiyo Petroleum, owns a 60% interest in an oil block that contains the Aje offshore field.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/folawiyo.jpeg")
	},
	{
		first_name: "2face",
		middle_name: "",
		last_name: "Idibia",
		job: "Artist",
		education: "",
		age: 40,
		source1: "entertainment",
		source2: "music industry",
		source3: "self made",
		net_worth: "1.5 Billion",
		description: "Innocent Ujah Idibia, better known by his stage name 2face Idibia, is a Nigerian singer-songwriter, record producer and entrepreneur. He officially discontinued the use of the name Tuface and selected 2baba or Tu-baba as his stage name.The multi-platinum former lead vocalist for Plantashun Boyz is the richest solo entertainer on the list. With an estimated worth of about N600 million (US$3.47 million), and endorsements from firms like Guinness and Airtel, and has also made heavy investments in real estate and stocks.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/idibia.jpg")
	},
	{
		first_name: "Genevieve",
		middle_name: "",
		last_name: "Nnaji",
		job: "Artist",
		education: "",
		age: 37,
		source1: "entertainment",
		source2: "movie industry",
		source3: "",
		net_worth: "1 Billion",
		description: "Genevieve Nnaji is a Nigerian actress and singer. She won the Africa Movie Academy Award for Best Actress in a Leading Role in 2005.",
		mycountry: "Nigeria",
		mystate: "Lagos",
		avatar: File.open("/Users/chineduabalogu/Documents/Important\ docs/famescan\ old/images/idibia.jpg")
	},
	{
		first_name: "Jannie",
		middle_name: "",
		last_name: "Mouton",
		job: "CEO of PSG Group",
		education: "",
		age: 69,
		source1: "Financial services",
		source2: "Self Made",
		source3: "",
		net_worth: "319.6 Billion",
		description: "The 69-year-old self-made billionaire is the founder of CEO of PSG Group, a listed investment holding company with interests in banking, financial services, agriculture, private equity and education.",
		mycountry: "South-Africa",
		mystate: "Stellenbosch",
		avatar: File.open("http://specials-images.forbesimg.com/imageserve/1f8b29d81374dbc7a02287a8f0ed74e8/320x486.jpg?fit=scale&background=000000")
	}
]
